configuration:
  configuration_dir: "git://github.com/pyecharts/pyecharts-mobans!/config"
  template_dir:
  - "git://github.com/moremoban/pypi-mobans?branch=dev&submodule=True!/templates"
  - "git://github.com/pyecharts/pyecharts-mobans!/templates"
  - ".moban.d"
  configuration: pyecharts-snapshot.yml
targets:
  - README.rst: custom_readme.rst.jj2
  - setup.py: snapshot_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - .travis.yml: pyecharts_travis.yml.jj2
  - .gitignore: pyecharts_gitignore.jj2
  - test.sh: test.script.jj2
  - output: CHANGELOG.rst
    template: CHANGELOG.rst.jj2
  - lint.sh: lint.script.jj2
  - Makefile: Makefile.jj2