requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
configuration:
  template_dir:
  - "pypi-mobans:templates"
  - ".moban.d"
  configuration: pyecharts-snapshot.yml
targets:
  - setup.py: setup.py
  - requirements.txt: requirements.txt.jj2
  - test.sh: test.sh.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
